name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node and publish
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-dockerhub:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Hub login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login \
            --username "${DOCKER_USERNAME}" \
            --password-stdin
      - name: Run buildx and push
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag ${DOCKER_REPO}:${GITHUB_REF#refs/tags/v} \
            --tag ${DOCKER_REPO}:latest \
            --file ./docker/java/Dockerfile .
      - name: Docker Hub logout
        if: always()
        run: docker logout